services:
    postgres:
        container_name: kitmakesthingsv4
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=root
            - POSTGRES_DB=kitmakesthingsdb
